clicepfl/clic-website

src/router.ts
=> Removed beta events page from router (fix)

src/pages/coaching/coaching-page-view.njk, src/sass/style.sass
Coach pictures were wrongly aligned depending on the browser. Seems to be the fix
=> (94) Hotfix coach pictures

src/pages/about/about-page-view.njk
Changed link to the statuses in the about section
=> Changed the link to the status

src/pages/icbd/icbd-page-view.njk
Registration form & event location.
=> ICBD page quick fixes

package-lock.json
`npm audit fix` for some recent vulnerabilities in dependencies. See https://github.com/clicepfl/clic-website/issues/17#issuecomment-804013818.
=> Hotfix: update dependencies with vulnerabilities

.github/workflows/main.yml, .gitignore, jest.config.js, package-lock.json, package.json, src/components/committee/committee.test.ts, src/components/news/news.test.ts, src/components/sponsors/sponsors.test.ts
- Adds yml config for NodeJS CI on Github Actions
- Add Jest testing framework
- Add smoke tests to check the shape of editable content (sponsors, news, committee)
=> Add Github Actions and Jest tests

src/components/sponsors/sponsors-list.json
=> Fix SICPA logo display on mobile

package-lock.json
Update dependencies with vulnerabilities, see #17
=> Update dependencies with npm audit fix

src/pages/coaching/coaching-page-view.njk
=> Nouveau lien du groupe BA1

src/pages/events/icbd/icbd-page-view.njk
juste modifié les textes + planning pour la page icbd
=> 252 kevin icbd

src/pages/events/icbd/icbd-speakers.json
=> Fix #274: File name conflict

src/pages/events/icbd/icbd-page-view.njk, src/sass/style.sass
... and a few other textual changes.
=> Add registration link

src/pages/events/icbd/icbd-page-view.njk
swap Networking Lunch & Speed Dating with Specialization Talks for display purposes
=> Swap ICBD cards

src/pages/about/poles/assets/com.md
Minor changes on communication page
=> 130 noe news

src/components/committee/committee-list.json, src/pages/about/poles/pole-list.json
- Change name Sponsoring to Partenariats
- Change name Evenementiel to Animation
- Type in "Harold Bernoit" (home page)
=> Fix few shells on committee update

src/components/news/content/41/body.md
=> typo news CLIC & MIL@Campus

src/pages/events/icbd3/icbd-page-view.njk
=> correct typo

src/pages/events/icbd3/icbd-page-view.njk, src/sass/style.sass
- add presentation video
- Commented PhD student list until it is available
=> feat: add presentation video, and remove PhD student list temporarily

src/pages/events/icbd3/icbd-page-view.njk, src/pages/events/icbd3/icbd-speakers.json, src/sass/style.sass, src/sass/timetable.sass
Small changes for more accuracy on Loan's presentation title
=> 252 tom icbd

src/pages/events/icbd3/icbd-speakers.json
add affiliation to Chaabouni Rafik
=> feat: update speakers list

src/components/news/content/49/body.md
=> remove dedondant info

src/components/news/content/49/body.md
To be merge when we have the HOLY MEDIACOM VALIDATION
=> change room BC420 to polydome

.dockerignore, .github/workflows/docker-publish.yml, .github/workflows/main.yml, Dockerfile, src/server.ts
Closes #397
- Adds Dockerfile
- Adds Github Actions workflow to build Docker image
- Fixes handling `SIGINT` and `SIGTERM`
=> feat: dockerize web server

src/pages/events/icbd5/icbd-page-view.njk
=> feat: add some descriptions
